// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package model

import (
	"github.com/google/uuid"
)

type Product struct {
	ID    uuid.UUID
	Sku   string
	Name  string
	Price float64
}
